name: Reset APT repo
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Reset history
        run: |
          git branch gh-pages || true
          git switch gh-pages
          git reset --hard origin/main
          git push --set-upstream origin -f gh-pages
